package hu.mudm.icefield.view;

import javax.swing.*;

public class MenuView extends MVCView {

    private JFrame mainFrame;   //Ezt kell majd használni a lenti öröklős megoldás helyett

    public MenuView(MVCModell modell) {
        super(modell);
    }

    @Override
    public void update() {

    }
}

//----------------------------------------------------------//
//           Jó tanácsok aki hozzányúl a lenti kódhoz:      //
//                                                          //
// A jlabel9 kuka, helyetta az ő paneljére rajzolunk majd   //
// Azért van ott, hogy amíg a rajzolás nincs megírva, lássuk//
// A játékmezőt.                                            //
//                                                          //
// A változókat érdemes refactorolni, mert így használha-   //
// tatlanok. //TODO Domi                                    //
//----------------------------------------------------------//


//public class MainFrame extends javax.swing.JFrame {
//
//    /**
//     * Creates new form MainFrame
//     */
//    public MainFrame() {
//        initComponents();
//    }
//
//    /**
//     * This method is called from within the constructor to initialize the form.
//     * WARNING: Do NOT modify this code. The content of this method is always
//     * regenerated by the Form Editor.
//     */
//    @SuppressWarnings("unchecked")
//    // <editor-fold defaultstate="collapsed" desc="Generated Code">
//    private void initComponents() {
//
//        jPanel1 = new javax.swing.JPanel();
//        jLabel9 = new javax.swing.JLabel();
//        jLabel1 = new javax.swing.JLabel();
//        jPanel2 = new javax.swing.JPanel();
//        jLabel3 = new javax.swing.JLabel();
//        jLabel2 = new javax.swing.JLabel();
//        jPanel3 = new javax.swing.JPanel();
//        jTextField1 = new javax.swing.JTextField();
//        jLabel5 = new javax.swing.JLabel();
//        jLabel4 = new javax.swing.JLabel();
//        jComboBox1 = new javax.swing.JComboBox<>();
//        jButton1 = new javax.swing.JButton();
//        jScrollPane1 = new javax.swing.JScrollPane();
//        jList1 = new javax.swing.JList<>();
//        jLabel6 = new javax.swing.JLabel();
//        jPanel4 = new javax.swing.JPanel();
//        jLabel7 = new javax.swing.JLabel();
//        jLabel8 = new javax.swing.JLabel();
//        jMenuBar1 = new javax.swing.JMenuBar();
//        jMenu1 = new javax.swing.JMenu();
//        jMenuItem1 = new javax.swing.JMenuItem();
//        jMenuItem4 = new javax.swing.JMenuItem();
//
//        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
//        setTitle("Icefield");
//
//        jPanel1.setBackground(java.awt.SystemColor.window);
//        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//
//        jLabel9.setIcon(new javax.swing.ImageIcon("D:\\BME\\Semester 4\\Projlab\\Icons\\field_sample.png")); // NOI18N
//
//        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
//        jPanel1.setLayout(jPanel1Layout);
//        jPanel1Layout.setHorizontalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(22, 22, 22)
//                                .addComponent(jLabel9)
//                                .addContainerGap(20, Short.MAX_VALUE))
//        );
//        jPanel1Layout.setVerticalGroup(
//                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel1Layout.createSequentialGroup()
//                                .addGap(22, 22, 22)
//                                .addComponent(jLabel9)
//                                .addContainerGap(21, Short.MAX_VALUE))
//        );
//
//        jLabel1.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
//        jLabel1.setText("<html><b>TestBunny</b>'s turn has started.</html>");
//        jLabel1.setToolTipText("");
//
//        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//
//        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel3.setIcon(new javax.swing.ImageIcon("D:\\BME\\Semester 4\\Projlab\\Icons\\researcher_mini.png")); // NOI18N
//        jLabel3.setToolTipText("");
//        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        jLabel2.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
//        jLabel2.setText("<html><b>TestBunny1</b>'s turn</html>");
//
//        jTextField1.setBackground(new java.awt.Color(240, 240, 240));
//        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
//        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
//        jTextField1.setText("5");
//        jTextField1.setBorder(null);
//        jTextField1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jTextField1ActionPerformed(evt);
//            }
//        });
//
//        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel5.setText("Temperature");
//
//        jLabel4.setBackground(java.awt.SystemColor.window);
//        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel4.setIcon(new javax.swing.ImageIcon("D:\\BME\\Semester 4\\Projlab\\Icons\\homero_tr.png")); // NOI18N
//        jLabel4.setToolTipText("");
//
//        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
//        jPanel3.setLayout(jPanel3Layout);
//        jPanel3Layout.setHorizontalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(13, 13, 13))
//                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jLabel4)
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        jPanel3Layout.setVerticalGroup(
//                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel3Layout.createSequentialGroup()
//                                .addGap(0, 0, 0)
//                                .addComponent(jLabel5)
//                                .addGap(7, 7, 7)
//                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
//        );
//
//        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<html><i>-Choose your next move-</i></html>", "Shovel", "Move", "Check icefloat capacity", "Build tent" }));
//
//        jButton1.setText("OK");
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jButton1ActionPerformed(evt);
//            }
//        });
//
//        jScrollPane1.setBorder(null);
//
//        jList1.setBackground(new java.awt.Color(240, 240, 240));
//        jList1.setModel(new javax.swing.AbstractListModel<String>() {
//            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
//            public int getSize() { return strings.length; }
//            public String getElementAt(int i) { return strings[i]; }
//        });
//        jList1.setFixedCellHeight(50);
//        jList1.setFixedCellWidth(50);
//        jList1.setLayoutOrientation(javax.swing.JList.HORIZONTAL_WRAP);
//        jList1.setMaximumSize(new java.awt.Dimension(250, 150));
//        jList1.setMinimumSize(new java.awt.Dimension(250, 50));
//        jList1.setPreferredSize(new java.awt.Dimension(250, 50));
//        jList1.setVisibleRowCount(-1);
//        jScrollPane1.setViewportView(jList1);
//
//        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel6.setIcon(new javax.swing.ImageIcon("D:\\BME\\Semester 4\\Projlab\\Icons\\akciok\\1.png")); // NOI18N
//        jLabel6.setToolTipText("");
//        jLabel6.setPreferredSize(new java.awt.Dimension(72, 72));
//
//        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
//        jPanel2.setLayout(jPanel2Layout);
//        jPanel2Layout.setHorizontalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGap(67, 67, 67)
//                                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addGap(26, 26, 26)
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jLabel2))
//                                                .addGap(18, 18, 18)
//                                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap())
//        );
//        jPanel2Layout.setVerticalGroup(
//                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(jPanel2Layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
//                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)))
//                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
//                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
//                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addContainerGap())
//        );
//
//        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
//
//        jLabel7.setFont(new java.awt.Font("Century Schoolbook", 0, 14)); // NOI18N
//        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
//        jLabel7.setText("<html>The icefloat you are standing on <br>\nhas 2 layers of snow.</html>");
//
//        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\BME\\Semester 4\\Projlab\\Icons\\layer2.png")); // NOI18N
//        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
//
//        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
//        jPanel4.setLayout(jPanel4Layout);
//        jPanel4Layout.setHorizontalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                .addGap(60, 60, 60)
//                                .addComponent(jLabel8)
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(21, 21, 21))
//        );
//        jPanel4Layout.setVerticalGroup(
//                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(jPanel4Layout.createSequentialGroup()
//                                .addContainerGap()
//                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(18, 18, 18)
//                                .addComponent(jLabel8)
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        jMenu1.setText("Options");
//
//        jMenuItem1.setText("Start");
//        jMenu1.add(jMenuItem1);
//
//        jMenuItem4.setText("Exit");
//        jMenu1.add(jMenuItem4);
//
//        jMenuBar1.add(jMenu1);
//
//        setJMenuBar(jMenuBar1);
//
//        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
//        getContentPane().setLayout(layout);
//        layout.setHorizontalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addContainerGap()
//                                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addGap(18, 18, 18)
//                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
//                                        .addGroup(layout.createSequentialGroup()
//                                                .addGap(33, 33, 33)
//                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//        layout.setVerticalGroup(
//                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
//                        .addGroup(layout.createSequentialGroup()
//                                .addGap(26, 26, 26)
//                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                .addGap(27, 27, 27)
//                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
//                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
//                                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
//                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
//                                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
//                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
//        );
//
//        pack();
//    }// </editor-fold>
//
//    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {
//        // TODO add your handling code here:
//    }
//
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainFrame().setVisible(true);
//            }
//        });
//    }
//
//    // Variables declaration - do not modify
//    private javax.swing.JButton jButton1;
//    private javax.swing.JComboBox<String> jComboBox1;
//    private javax.swing.JLabel jLabel1;
//    private javax.swing.JLabel jLabel2;
//    private javax.swing.JLabel jLabel3;
//    private javax.swing.JLabel jLabel4;
//    private javax.swing.JLabel jLabel5;
//    private javax.swing.JLabel jLabel6;
//    private javax.swing.JLabel jLabel7;
//    private javax.swing.JLabel jLabel8;
//    private javax.swing.JLabel jLabel9;
//    private javax.swing.JList<String> jList1;
//    private javax.swing.JMenu jMenu1;
//    private javax.swing.JMenuBar jMenuBar1;
//    private javax.swing.JMenuItem jMenuItem1;
//    private javax.swing.JMenuItem jMenuItem4;
//    private javax.swing.JPanel jPanel1;
//    private javax.swing.JPanel jPanel2;
//    private javax.swing.JPanel jPanel3;
//    private javax.swing.JPanel jPanel4;
//    private javax.swing.JScrollPane jScrollPane1;
//    private javax.swing.JTextField jTextField1;
//    // End of variables declaration
//}

